# Generated by Django 4.2.9 on 2024-02-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_file_upload", "0004_blog_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="", upload_to="output/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="file_upload",
            field=models.FileField(
                default="", max_length=250, null=True, upload_to="input/"
            ),
        ),
    ]
