# Generated by Django 4.2.9 on 2024-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_file_upload", "0005_blog_image_alter_blog_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="", upload_to="input/"),
        ),
    ]
