# Generated by Django 4.2.4 on 2024-02-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_file_upload", "0006_alter_blog_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog", old_name="file_upload", new_name="video",
        ),
    ]
