# Generated by Django 4.2.4 on 2024-02-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_file_upload", "0008_rename_name_blog_caption_alter_blog_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="video",
            field=models.FileField(
                default="", max_length=250, null=True, upload_to="input/"
            ),
        ),
    ]
