# Generated by Django 4.2.10 on 2024-02-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_file_upload", "0010_rename_video_blog_file_upload_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Blog", new_name="File",),
    ]
